#!/bin/bash

# Define el tamaño y centra la ventana cuando esté en modo floating
bspc rule -a Thunar state=floating rectangle=850x450+0+0 center=true follow=on

#bspc rule -a Thunar state=floating center=on rectangle=500x100+0+0

# Reglas para ventanas específicas
bspc rule -a kitty state=floating
#bspc rule -a Thunar state=tiled floating
#bspc rule -a Blueman-manager state=floating
#bspc rule -a Gimp state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Windscribe2 state=floating
bspc rule -a org-tlauncher-tlauncher-rmo-TLauncher state=floating
bspc rule -a pamac-installer state=floating

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a audacious state=floating
bspc rule -a vlc state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# File manager en workspace 1
#bspc rule -a Nautilus desktop='1'

# Code editors en workspace 2
bspc rule -a code desktop='^2'
bspc rule -a sublime_text desktop='^2'
bspc rule -a dev.zed.Zed desktop='^2'

# Terminal en workspace 2
#bspc rule -a kitty desktop='^3'

# Firefox en workspace 4
bspc rule -a firefox-esr desktop='^4' follow=on
bspc rule -a Brave-browser desktop='^4'

# Workspace 5
bspc rule -a GitHub Desktop desktop='5'

# Workspace 6
bspc rule -a Insomnia desktop='6'

# Workspace 7
bspc rule -a Audacious desktop='^7'
bspc rule -a vlc desktop='^7' follow=on



