#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xsetroot -cursor_name left_ptr &

#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width        1
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Picom
picom -b --backend glx &

# Wallpaper
#feh --bg-fill ~/Imágenes/27.jpg &

# Colors
bspc config normal_border_color   "#0076ff"
bspc config focused_border_color  "#5294e2"
bspc config active_border_color   "#976562"
bspc config presel_feedback_color "#5294e2"
i
# Autostart
~/.config/bspwm/scripts/autostart.sh &

# Panel 
#~/.config/bspwm/scripts/panel.sh &

# Rules
~/.config/bspwm/rules/bspwm_rules 
