#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Workspaces
#bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor -d "  " " 󰨞  " "   " " 󰈹 " " 󰊢 " " " "  " "  "  "  "

#bspc monitor -d 1 2 3 4 5 6 7 8 9 10



bspc config border_width         1
bspc config window_gap           1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Picom
picom -b --backend glx &

# Wallpaper
feh --bg-fill ~/Imágenes/01.png &

#xsetroot -cursor_name left_ptr &
#xset r rate 300 50 &

~/.config/bspwm/scripts/panel.sh &


# Colors
# Colores
bspc config normal_border_color   "#2c5380"
bspc config focused_border_color  "#5294e2"
bspc config active_border_color   "#5294e2"
bspc config presel_feedback_color "#5294e2"

# Autostart
~/.config/bspwm/scripts/autostart.sh
